### ISSUE TITLE
"Chat Plays OBS" TitleBar component text should scale so that it stays on 1 line

### ISSUE THREAD

**Issue by dustinbowers** [MAItisse/streamerTwitchJam#11]
**NOTE**: this is in the `postHackathon` branch

TitleBar component: https://github.com/MAItisse/streamerTwitchJam/blob/postHackathon/streamerAppOBS/src/components/TitleBar.vue

This is what needs some extra styling
```ts
<!-- Logo -->
<h1 class="inline-block bg-gray-100 rounded-full text-xl font-extrabold text-gray-800 tracking-wide shadow-sm px-3">
               Chat Plays <span class="text-blue-600">OBS</span>
</h1>
```

We can add a media query in the CSS here: https://github.com/MAItisse/streamerTwitchJam/blob/postHackathon/streamerAppOBS/src/assets/scss/index.scss
```css
.title-bar {
    background: $palette-1;

    h1{ /* ... */ }
}
```

**Comment by MatissesProjects** [comment]
nice this makes sense
we should be able to start integrating this into the main tomorrow!
I might be inclined to wait till the weekend though

**Comment by MatissesProjects** [comment]
This fix is now in main
